### ISSUE TITLE
Add Rules for Official Mods released by Bethesda

### ISSUE THREAD

**Issue by MacSplody** [loot/morrowind#1]
Original files can be found here [official plugins released by Bethesda](https://en.m.uesp.net/wiki/Morrowind:Plugins)

List of official plugins:
`adamantiumarmor.esp`
`AreaEffectArrows.esp`
`bcsounds.esp`
`master_index.esp`
`EBQ_Artifact.esp`
`entertainers.esp`
`LeFemmArmor.esp`
`Siege at Firemoth.esp`

Plugins are patched or replaced in:
  - [Gold Armor Reforged](https://www.nexusmods.com/morrowind/mods/42560)
  - [Official Mods Compilation](https://www.nexusmods.com/morrowind/mods/3882)
  - [Unofficial Morrowind Official Plugins Patched](https://www.nexusmods.com/morrowind/mods/43931)
  - [Morrowind Official Plugins by WHReaper](http://download.fliggerty.com/download-13-1079)

---

- [x] Sorting Rules
- [x] Already Included in Messages.
- [x] Compatibility.
- [x] Deactivate plugins, Merged Versions Require Assets.

**Comment by Tyler799** [comment]
* The order of the official addons (to each other) doesn't matter
* Official addons (or things like OMC, UMOPP, MOP) should be after Patch for Purists (or the Morrowind Patch Project, not that anyone should be using it)

Just noting for later

**Comment by MacSplody** [comment]
>     * The order of the official addons (to each other) doesn't matter

@Tyler799 Are these plugins loaded before everything else? Or it doesn't really matter?

>     * Official addons (or things like OMC, UMOPP, MOP) should be after Patch for Purists (or the Morrowind Patch Project, not that anyone should be using it)

LOOT will automatically place `ESM` plugins before non `ESM` plugins.

The right side is manual placement, and the left is the order when LOOT first loads up.

![image](https://user-images.githubusercontent.com/1944639/56840444-7a176680-687f-11e9-83f1-8297e5248246.png)

**Comment by Tyler799** [comment]
> Are these plugins loaded before everything else? Or it doesn't really matter?

Doesn't matter *most* of the time. For safety, I'd do Morrowind -> DLCs -> Patch for Purists -> Official addons.

Theoretically the addon placement doesn't really matter much at all in the load order, but there are a couple nagging cases where mods depend on the official addons like how TR_Preview.esp needs to load after firemoth. 

So I think it's best to put them early.

**Comment by pStyl3** [comment]
Since the official mods are official Bethesda content, I'd agree that they should load early, and @Tyler799 's suggestion seems fine for me.

If the order of them amongst each other doesn't matter much, maybe order them in the order they were published? Do we know in which order they got released?

**Comment by pStyl3** [comment]
We do know the release order:
10.05.2002 - ``entertainers.esp``
31.05.2002 - ``bcsounds.esp``
31.05.2002 - ``AreaEffectArrows.esp``
14.06.2002 - ``EBQ_Artifact.esp``
21.06.2002 - ``master_index.esp``
01.07.2002 - ``LeFemmArmor.esp``
02.08.2002 - ``adamantiumarmor.esp``
13.09.2002 - ``Siege at Firemoth.esp``
