### ISSUE TITLE
Integrate changes from mlox-rules

### ISSUE THREAD

**Issue by poperigby** [loot/morrowind#111]
There's a big list of rules that could integrated into this master list: https://github.com/DanaePlays/mlox-rules

It would be good to cut down on duplicate work.

**Comment by pStyl3** [comment]
The LOOT team already discussed the possibility of converting the mlox ruleset, first in [this GitHub issue](https://github.com/loot/loot/issues/1101), then later on Discord [here](https://discord.com/channels/473542112974077963/473721823071043585/1015294580721192960) and [here](https://discord.com/channels/473542112974077963/473543945188802580/1208646542110494820) once more.

We currently are not in favor of converting mlox's rules for a number of reasons.

![image](https://github.com/user-attachments/assets/e4626014-9e68-4fa9-8b60-8807d7ce74a3)

![image](https://github.com/user-attachments/assets/14ae5613-00ce-496b-a22d-03fba5ffd0db)
