### ISSUE TITLE
Add mods to incompatible list with Patch for Purists

### ISSUE THREAD

**Issue by Tyler799** [loot/morrowind#3]
The following ESPs/ESMs are incompatible with Patch for Purists (any of its modules could be checked against, but I'd do Patch for Purists - Base Patch.esm since it makes the most sense) 

This info is from the description: https://www.nexusmods.com/morrowind/mods/45096?tab=description

Other morrowind patches (Unofficial Morrowind Patch (UMP), Morrowind Patch Project (MPP)):

* Morrowind Patch v1.2.2.esm
* Morrowind Patch v1.6.3.esm
* Morrowind Patch v1.6.4.esm
* Morrowind Patch v1.6.5-BETA.esm
* Morrowind Patch 1.6.5 Beta (BTB Edit).esm
* Morrowind Patch v1.6.5d_beta.esm
* Morrowind Patch v1.6.6_beta.esm

* gr_ScriptImprovements.esp
* gr_ScriptImprovements.esm

From Morrowind rebirth:

* Morrowind Rebirth [Main].ESP 

I'd assume you can just check against that one, but just in case, here's the rest:

* Dramatic Vivec [For Rebirth].esp
* Holamayan Monastery Replacer [For Rebirth].esp
* Illegal Dwemer Trading [For Rebirth].esp
* Julan Ashlander Companion 2.02 [For Rebirth].esp
* Solstheim TotSP [For Rebirth].esp
* Uvirith's Legacy_3.53 [For Rebirth].esp
* Morrowind Rebirth - Birthsigns [Addon].ESP
* Morrowind Rebirth - Game Settings [Addon].ESP
* Morrowind Rebirth - Mercenaries [Addon].ESP
* Morrowind Rebirth - Races [Addon].esm
* Morrowind Rebirth - Skills [Addon].ESP
* Morrowind Patch Project 1.6.5 [For Rebirth].esm

**Comment by MacSplody** [comment]
> From Morrowind rebirth:
> 
>     * Morrowind Rebirth [Main].ESP
> 
> 
> I'd assume you can just check against that one, but just in case, here's the rest:

If `Morrowind Rebirth [Main].esp` is a master for those plugins then yes.
