### ISSUE TITLE
Add Beautiful Cities of Morrowind and patches

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/morrowind#52]
### [Beautiful Cities of Morrowind](https://www.nexusmods.com/morrowind/mods/49231/)

Sources:
[BCoM BAIN installation details](https://docs.google.com/document/d/1mO75n7f6X6EH1SmmQ-CmPHvdPbH30Q3OWyn-PDSCnys/edit?usp=sharing)
[Mlox rules](https://github.com/DanaePlays/mlox-rules/blob/main/mlox_user.txt)
Included readme files

---

#### Core files
`Beautiful cities of Morrowind.ESP`
`BOM_pathgrid_reset.esp`
`Interior exterior flag reset.ESP`

- Check MLOX rules for core files, and test against LOOT sorting. (Optional, as that could take some time)

---

#### Optional files

`SOP_RichPlaza_IziStyle.ESP` Haalu Council Hall Plaza - Izy Style
- Incompatible with `Brevur of Balmora - Finally Some Good Statue Mod.ESP`.
- Marking them as incompatible once is enough.

`SOP_Canal_01.ESP` Riverside - Simple Cluttering
- Appears as part of load order for some other mods.

`SOP_Canal_02.ESP` Riverside - Stone Dock

`BOM_OpenMW_plazas.ESP` Weather Mechanics for OpenMW

`BCOM_Suran Expansion.ESP` Suran dock expansion & clutter addon

`BOM_White_Suran.ESP` White Suran
- Similar to [White Suran 2 - MD Edition](https://www.nexusmods.com/morrowind/mods/44153/).

`BOM_Stavs_MGO.ESP` Stav's Mages Guilds

`BOM - Taller Lighthouse.ESP` Taller Lighthouse

`BOM_Sadrith_Mora_dock_expanded.ESP` Expanded Sadrith Mora Dock
- No mentions in Mlox rules file

---

#### Patches

`Patch for Purists.esm` [Patch for Purists](https://www.nexusmods.com/morrowind/mods/45096/)
- [x] Patch included in installer `BOM_PfP_patch.ESP`.

`Rise of House Telvanni.esm` [Rise of House Telvanni](https://www.nexusmods.com/morrowind/mods/27545/)
- [x] Patch included in installer `BOM_ROHT_Patch.ESP`.

---

#### Replacement Plugins

`abotBoats.esp` [Boats](https://www.nexusmods.com/morrowind/mods/42270/)
- [ ] Requires Resources from original mod.
- [ ] Patch `BOM_abot_boats.esp` included in installer.

`Animated_Morrowind - merged.esp` [RandomPal's random mods and patches](https://www.nexusmods.com/morrowind/mods/48683/)
- [ ] Requires Resources from original mod.

`Brevur of Balmora - Finally Some Good Statue Mod.ESP` [Brevur of Balmora - Finally Some Good Statue Mod](https://www.nexusmods.com/morrowind/mods/47557/)
- [x] Requires Resources from original mod.
- [x] Incompatible with Izy Style Standalone `SOP_RichPlaza_IziStyle.ESP`.

`Foyada Mamaea Overhaul.ESP` [Foyada Mamaea Overhaul](https://www.nexusmods.com/morrowind/mods/46424/)
- [ ] Requires Resources from original mod, if using version with CRC 2978B483.
- [ ] Use version for Red Mountain Reborn if that's installed. CRC E68E1B2C

`GITD_Telvanni_Dormers.ESP` [Glow in the Dahrk](https://www.nexusmods.com/morrowind/mods/45886/)
- [ ] Requires Resources from original mod.

`Improved Inns Expanded.esp` [Improved Inns Expanded](https://www.nexusmods.com/morrowind/mods/48610/)
- Could be added as a patch included message, but we could add a new message for replacement plugins.
- No resources required.

`Improved Inns Expanded - Entertainers.ESP` [Improved Inns Expanded](https://www.nexusmods.com/morrowind/mods/48610/)
- Could be added as a patch included message, but we could add a new message for replacement plugins.
- No resources required.

`MQE_MainQuestEnhancers.esp` [Main Quest Enhancers](https://www.nexusmods.com/morrowind/mods/41337/)
- Could be added as a patch included message, but we could add a new message for replacement plugins.
- No resources required.

`RedMountainReborn.esp` [Red Mountain Reborn](https://www.nexusmods.com/morrowind/mods/48669/)
- [ ] Requires Resources from original mod.

`ROHT_2_0_8.ESP` [Rise of House Telvanni - 2.0](https://www.nexusmods.com/morrowind/mods/48225/)
- [ ] Requires Resources from original mod. And [Rise of House Telvanni](https://www.nexusmods.com/morrowind/mods/27545)
- [ ] Incompatible with `BOM_ROHT_Patch.ESP`.

`Siege at Firemoth.esp` [Unofficial Morrowind Official Plugins Patched](https://www.nexusmods.com/morrowind/mods/43931/) - UMOPP 3.1.0
- [ ] Requires Resources from original mod.

---

To be continued with adding patches for mods and mods themselves.
This also may be treated as a "transcribe "fresh" Mlox rules into LOOT" as almost 1/2 or 3/4 of them are for BCOM and related mods and/or patches.

**Comment by MacSplody** [comment]
> to be continued with adding patches for mods and mods themselves

For each mod that requires a replacement plugin, some might need a separate issue.
We could check the current [MLOX rules](https://github.com/DanaePlays/mlox-rules/blob/main/mlox_user.txt) list to see if there's any metadata that could be added.

> (and of course formatting broke and there are newlines everywhere. Why? No idea.)

It usually needs a newline after each bulleted, numbered and task list.
I tidied it up a bit to make the tasks easier to manage.

**Comment by MacSplody** [comment]
Full list of files for reference.

00 Core
`BOM_pathgrid_reset.esp`
`Beautiful cities of Morrowind.ESP`
`Interior exterior flag reset.ESP`

01 Haalu Council Hall Plaza - Brevur of Balmora
`Brevur of Balmora - Finally Some Good Statue Mod.ESP`

01 Haalu Council Hall Plaza - Izy Style
`SOP_RichPlaza_IziStyle.ESP`

01 Haalu Council Hall Plaza - Vanilla Trees
`BOM_Vanilla Trees.ESP`

02 Riverside - Simple Cluttering
`SOP_Canal_01.ESP`

02 Riverside - Stone Dock
`SOP_Canal_02.ESP`

03 Weather Mechanics for OpenMW
`BOM_OpenMW_plazas.ESP`

04 Suran dock epansion&clutter addon
`BCOM_Suran Expansion.ESP`

05 White Suran
`BOM_White_Suran.ESP`

06 Stav's Mages Guilds
`BOM_Stavs_MGO.ESP`

07 Taller Lighthouse
`BOM - Taller Lighthouse.ESP`

08 Expanded Sadrith Mora Dock
`BOM_Sadrith_Mora_dock_expanded.ESP`

09 Patch for Purists Patch
`BOM_PfP_patch.ESP`

10 Red Mountain Reborn
`RedMountainReborn.esp`

11 Foyada Mamaea Overhaul
`Foyada Mamaea Overhaul.ESP`

11 Foyada Mamaea Overhaul - Red Mountain Reborn
`Foyada Mamaea Overhaul.ESP`

12 Main Quest Enhancers
`MQE_MainQuestEnhancers.esp`

13 Animated Morrowind
`Animated_Morrowind - merged.esp`

13 Animated Morrowind for OpenMW
`Animated_Morrowind - merged - OpenMW.esp`

14 Improved Inns Expanded
`Improved Inns Expanded.esp`

14 Improved Inns Expanded- Entertainers
`Improved Inns Expanded - Entertainers.ESP`

15 Rise of House Telvanni
`BOM_ROHT_Patch.ESP`

15 Rise of House Telvanni 2.0
`ROHT_2_0_8.ESP`

16 Siege at Firemoth
`Siege at Firemoth.esp`

17 GITD Telvanni Dormers
`GITD_Telvanni_Dormers.ESP`

18 Abots Boats - TR - activate both esp
`BOM_abot_boats.esp`
`abotBoatsTR2101.esp`

18 Abots Boats - activate both esp
`BOM_abot_boats.esp`
`abotBoats.esp`

19 Abot's boats patch for Tomb of the Snow Prince
`TOTSP_abotBoats.esp`

19 Abot's boats patch for Tomb of the Snow Prince - TR
`TOTSP_abotBoats.esp`

20 Abot's gondoliers - activate both esp
`abotGondoliers.esp`
`abotGondoliers_RVP.esp`

21 Abots Silt Striders
`BOM_AbotSiltStriders.ESP`
`abotSiltStriders.esp`

21 Abots Silt Striders - TR
`BOM_AbotSiltStriders.ESP`
`abotSiltStridersTR2101.esp`

22 TR_Travels
`TR_Travels Patch.ESP`

22 TR_Travels (Mainland and Preview)
`TR_Travels_(P_M) Patch.ESP`

23 Welcome to the Arena
`Welcome_to_the_Arena_v6.7_OV.esp`

23 Welcome to the Arena - OpenMW
`Welcome to the Arena! v6.7.esp`

24 Skyrim Home of The Nords Patch
`SHOT_patch.ESP`

25 Province Cyrodiil Patch
`PC_patch.ESP`

26 RR Ships and Boats
`RR_Better_Ships_n_Boats_Eng.esp`

27 Ebonheart Underworks
`Ebonheart_Underworks.esp`

28 Cephalopod armor
`Cephalopod armor_BOM_patch.ESP`
`RR_Cephalopod Armor_BOM_patch.ESP`

29 Yet Another Guard Diversity - Cephalopod Armor
`Yet Another Guard Diversity - Full Cephalopod.ESP`

29 Yet Another Guard Diversity - RR Cephalopod Armor
`Yet Another Guard Diversity - Better Telvanni Cephalopod Armor.ESP`

29 Yet Another Guard Diversity - Regular
`Yet Another Guard Diversity - Regular.ESP`

30 Morrowind Anticheese
`Morrowind Anti-Cheese.ESP`

31 LGNPC FQ
`LGNPC_VivecFQ.esp`

32 Apartments of Morrowind
`Apartments of Morrowind.ESP`

33 The Great Scathes
`The Great Scathes.ESP`

34 Imperial Employment Office
`Imperial Employment Office (MD edits).esp`

35 Mines and Caverns
`Clean_Mines & Caverns.esp`

35 Mines and Caverns - RMR Compatible
`Clean_Mines & Caverns.esp`

36 Suran Underworld
`BCOM_suran underworld_expansion patch.ESP`
`Suran_Underworld_v3.ESP`

36 Suran Underworld - TOTSP
`BCOM_suran underworld_expansion patch.ESP`
`Suran_Underworld_v3.ESP`

37 Welcome Home
`Welcome Home - BOM.esp`

37 Welcome Home - TOTSP
`Welcome Home - BOM.esp`

38 Bounty Hunter Bundle
`Bounty_Hunter_BUNDLE.ESP`

39 Ashlander Traders Remastered
`Ashlander Traders Remastered.esp`

40 Holidays Across Tamriel
`Holidays Across Tamriel - Vvardenfell - RR Holamayan mod.esp`

41 Realistic Repair Addon
`Realistic_Repair_Add-on.ESP`

42 True Light and Darkness Patch
`TLAD Full - Still - Necro Colors.esp`

43 Uvirith Legacy Patch
`BOM - Uvirith''s Legacy.esp`

44 Correspondances of Morrowind
`Correspondances_of_Morrowind.esp`

45 Unique banners and signs
`Unique Banners and Signs.esp`

46 Vality's Bitter Coast
`Valitys_Bitter_Coast_Addon.esp`

46 Vality's Bitter Coast for Vurt's BC Trees
`Vurt''s BC Tree Replacer II + vality bitter coast.ESP`

47 NPC Schedules
`NPC_Schedule(beta).esp`

48 Velothi Wall Art
`Velothi Wall Art Re-Addon.ESP`
`Velothi Wall Art.ESP`

49 MWSE Containers
`mwse_Containers.esp`

50 Julan The Ashlander Companion
`KS_Julan_Ashlander Companion_3.0_beta.esp`

52 Starfire npcs addition
`Starfires_NPC_Additions_ver-1.13_RP.esp`

52 Starfire npss additions - only interiors and telemages
`Starfires NPC Additions ver1.13_RP_interiors_only.esp`

53 Morag Tong Expanded
`Morag Tong Expanded.esp`

54 Area of effect Arrows
`AreaEffectArrows.esp`

55 Guild of Vampire hunters
`Guild of Vampire Hunters.ESP`

56 Dartboards expanded
`DartboardsExpanded.esp`

57 Sload and Slavers
`Sload and Slavers.ESP`

58 Racer Dust Arms and Armor
`Racer Dust Arms and Armor.ESP`

59 Redoran Patrols
`Redoran Patrols - Gnisis.ESP`

60 Traveling Merchants
`TravelingMerchants_v2_3.esp`

60 Traveling Merchants - Stonewood pass reworked
`TravelingMerchants_v2_3.esp`

61 Dura_Gra-Bols_House_Reclaimed
`Dura Gra-Bol''s House Reclaimed.ESP`

62 An issue of thrust
`OAAB An Issue Of Thrust.ESP`

63 Lights Ald-ruhn
`Lights Ald-ruhn.ESP`

64 The Publicans
`The Publicans.ESP`

65 Imperials Go Home
`Imperials Go Home v1.esp`

66 Gildergreen patch
`BOM_Gildergreen_pathgrid_patch.ESP`
`GildergreenOfBalmora.esp`

67 Balmora Docks
`BalmoraDocks.ESP`

68 Moonlight On the Odai River
`MoonlightOnTheOdaiRiver.esp`

69 Glass Domes
`Glass Domes of Vivec.esp`

70 The Cottage
`The Cottage.ESP`

71 Pillow Mage Manor
`Pillow_Mage_Manor.esp`

72 No trespassing - Merged
`No trespassing.ESP`

73 Store Entrance Chimes
`Store Entrance Chimes - Alt Ver.ESP`

74 Striderport Lights
`BCOM_Striderport Lights.ESP`

75 The Sanguine Rose
`The Sanguine Rose.ESP`

76 High Art
`High Art.esp`

77 LGNPC Pax Redoran
`LGNPC_PaxRedoran.esp`

78 Dance of the Three Legged Guar
`DanceoftheThreeLeggedGuar.esp`

79 Faction Living Quarters
`Living Quarters.esp`

80 Main Quest Overhaul
`Main_Quest_Overhaul.ESP`

81 Mamaea Awakened
`Mamaea Awakened.ESP`

82 Vivec City
`Vivec_Clutter.ESP`
`Vivec_Lights.ESP`
`Vivec_Street Vendors.ESP`

83 NX9 Buyable Houses
`NX9_Houses_BCOM _no_clutter.ESP`
`NX9_Houses_BCOM.ESP`
`NX9_Houses_BCOM_pathgrid_reset.ESP`

84 Scrolls of the nine barriers
`BOM_Scrolls of the Nine Barriers_patch.ESP`

85 Illuminated Order Improved
`Illuminated Order Improved.ESP`

87 Master Index Redux
`MasterIndexRedux.esp`

88 Red Mountain Reborn - Kogoruhn Expanded patch-fix
`RMR_KogoruhnExp_patch.ESP`

89 Mandas Manor
`MandasManor.ESP`

90 Arvesa - An Armingers Tale (patch)
`BCOM_Arvesa_patch.ESP`

**Comment by IllusiveMan196** [comment]
Well, this looks even more intimidating than long list in odt document...

**Comment by MacSplody** [comment]
> Well, this looks even more intimidating than long list in odt document...

It does, but if you break it up into tasks it will be a lot easier.
Some of those files might not even need any metadata.

**Comment by IllusiveMan196** [comment]
Work is slowly moving towards having actually somewhat complete-ish masterlist. I've given up on tracking it though, so this issue probably will stay until listed mods are checked off and then closed.
